### ISSUE TITLE
Are JavaScript modules compiled or run natively?

### ISSUE THREAD

**Issue by jkrems** [vsls-contrib/gistpad#119]
When creating a new playground with JavaScript modules, it's creating a `.js` files. This usually suggests that the module syntax is bundled or compiled away (e.g. to CommonJS). I tried to rename to `.mjs` but that seems to have broken execution. Is there are way to use uncompiled modules / `.mjs` files?

**Comment by lostintangent** [comment]
Hey! We’re not doing any bundling in order to support modules. We’re simply setting the script’s type attribute to “module”. So if you import other modules, they’d need to either be 1) a relative URL to another file in the same gist, or 2) an absolute URL that points at a JS module (e.g. using a CDN like Unpkg). 

Right now, a playground determines if it should use modules based on the scriptType property in its way playground.json file. That said, I can also add supoort for .mjs files as well. Do you think that the JS-only module template should generate an .mjs file? Would that be the more accurate solution?

**Comment by jkrems** [comment]
> Do you think that the JS-only module template should generate an .mjs file? Would that be the more accurate solution?

I'd personally find that more clear / easier to tell apart at first glance. But I think my primary concern would be that I  can safely rename it to `.mjs` without breaking the playground. If that is supposed to work, it could also be that I messed up at some point while trying out this plugin (which is great, btw!).

**Comment by lostintangent** [comment]
Sounds good. I’ll make this change so that when you create a new playground for a JS module, that it creates a “.mjs” file by default. Look out for that change later today 👍

**Comment by lostintangent** [comment]
Just shipped an extension update that includes this fix. Let me know if you run into any other problems. Thanks for the feedback!
