### ISSUE TITLE
Token security

### ISSUE THREAD

**Issue by pootzko** [vsls-contrib/gistpad#134]
Hi, this extension seems great, thanks for the good work!

Could you please let me know how the token is stored on the computer? I'm using [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) to sync up my VSCode settings, and I don't want my token to end up in a public gist by accident. 

Thanks!

**Comment by lostintangent** [comment]
Hey! Great question 👍 GistPad stores the token in your local OS keychain, and so it’s fully encrypted at rest, and it wouldn’t be accidentally synchronized. The settings sync extension doesn’t synchronize your keychain, which is good, since it shouldn’t ever do that!

I’m going to close this as resolved, but please let me know if you need any more details and/or if there’s anything else I could do to make sure that GistPad is as awesome as it could be. Thanks!

**Comment by RandomFractals** [comment]
good call on the encrypted part
