### ISSUE TITLE
GistPad interferes with other extensions 

### ISSUE THREAD

**Issue by YusufMohammedUH** [vsls-contrib/gistpad#153]
I have an VSCode v1.45.1 on Ubuntu 18.04. I noticed after updating to v1.45.1 that the enter and delete key didn't respond in within .tex files as well as .py files. Additionally the extension "Project Manager" didn't work. 

The issues do appear:
1. gistpad together with hungry delete : delete key doesn't delete characters and doesn't seem to 
                                                               respond
2. gistpad together with latex workshop: enter key doesn't result in a new line 

3. gistpad together with project manager: project manager doesn't respond (doesn't show projects most of the time some times it shows the projects, but I'm not able to open them )

All other extension were disabled during 1.-3..

Disabling GistPad

**Desktop:**
- VS Code Version v1.45.1
- GistPad v0.0.68
- Hungry Delete v1.6.0
- LaTeX Workshop v8.9.0
- Project Manager v11.0.1

**Comment by Marklb** [comment]
I seem to be having the same issue on v1.46.0, Windows 10.

I didn't have any of the other extensions enabled that you mentioned, but it seems like basically all my extensions stop do anything, for the most part, once GistPad starts. Its like there is something synchronous being done that never completes.
- Git Source Control doesn't finish loading.
- None of the intellisense seems works.
- If I hover anything in the editor, such as a function, that shows comments or some other information, it just shows 'Loading...'.
- Can't save without canceling any saveOnComplete actions, because none of them can complete.

To see if it was just interrupting the startup, I started VSCode with GistPad disabled and made sure the problems I listed above were working as I expected. Then I enabled GistPad without restarting and the problems started. So, git stopped detecting any changes, intellisense stopped providing any code completion, anything I hovered in the editor just shows 'Loading...', etc.

I don't know how far the initialization gets, but it doesn't log in. None of the GistPad buttons or commands seem to do or log anything that I can see. 

My office computer was working on v1.45.1, Windows 10. I restarted VSCode, which updated it to v1.46.0 and now it has the same problem.

**Comment by lostintangent** [comment]
@Marklb Thanks so much!!! I’ll try your change on macOS first thing in the morning. And if it looks good, I’ll ship this fix ASAP. Apologies for the issue here.

**Comment by Marklb** [comment]
After looking into this more, I don't know if my pull request is the right way to fix it. My problem seems to be more about the `GIT_ASKPASS` tool. It looks like the `GIT_ASKPASS` environment var isn't correctly set to use VSCode and instead is getting hung waiting for the username/password prompt to be inputed.

First I wrote a small nodejs script to see if `execSync` and `execFileSync` were using the same Git.
```js
const { execSync, execFileSync } = require('child_process')

console.log('execFileSync: where git')
console.log(execFileSync('where', ['git'], { encoding: 'utf8' }))

console.log('execFileSync: where git.exe')
console.log(execFileSync('where', ['git.exe'], { encoding: 'utf8' }))

console.log('execFileSync: where git.bat')
console.log(execFileSync('where', ['git.bat'], { encoding: 'utf8' }))

console.log('execSync: where git')
console.log(execSync('where git', { encoding: 'utf8' }))

console.log('execSync: where git.exe')
console.log(execSync('where git.exe', { encoding: 'utf8' }))

console.log('execSync: where git.bat')
console.log(execSync('where git.bat', { encoding: 'utf8' }))
```
Output:
```txt
execFileSync: where git
E:\Programs\depot_tools\git.bat
C:\Program Files\Git\cmd\git.exe

execFileSync: where git.exe
C:\Program Files\Git\cmd\git.exe

execFileSync: where git.bat
E:\Programs\depot_tools\git.bat

execSync: where git
E:\Programs\depot_tools\git.bat
C:\Program Files\Git\cmd\git.exe

execSync: where git.exe
C:\Program Files\Git\cmd\git.exe

execSync: where git.bat
E:\Programs\depot_tools\git.bat
```

So, with that I can tell why changing `execSync` to `execFileSync` worked for me. I have github credentials in the windows git, but not the depot_tools git. (I shouldn't even have the depot_tools version even on my PATH anymore, but I haven't been having any problems, so I forgot it was there.) Since `execFileSync` doesn't spawn a shell it must be skipping over my first git tool(`git.bat`) on my PATH and using the second(`git.exe`), which already had credentials, so the prompt wasn't needed.

Fixing the `GIT_ASKPASS` environment var to correctly use VSCode as its AskPass tool is what I am thinking the correct fix may be. I have got it to return an empty string if credentials don't exist using `%LOCALAPPDATA%/Programs/Microsoft VS Code/resources/app/extensions/git/dist/askpass-empty.sh` from VSCode's Git extension. If it should allow the prompt to work, I have got it to use VSCode as the AskPass tool, but I haven't figured out how to make it consistently use it correctly.

**Comment by lostintangent** [comment]
@Marklb Interesting! I was wondering why I couldn't repro this, and maybe it's because I don't have the `GIT_ASKPASS` env var set? Out of curiosity: did you set this manually? Or did some tool set this on your behalf?

@YusufMohammedUH By any chance, is the `GIT_ASKPASS` env var set for your as well? I'd love to narrow down whether this is the issue.

**Comment by Marklb** [comment]
@lostintangent I am not sure what is actually being used when I call `execSync` from the extension. From what I remember the environments spawned from VSCode inherit some of the VSCode specific vars by default, but I don't remember where I read that, so I am not positive. I think I had read it on something explaining how some scripts executed in the embedded terminal will try to use VSCode for things like the EDITOR if one hasn't been specified, but its been a while since I read about it.
There are at least three places the AskPass tool can be configured, based on the documentation(https://git-scm.com/docs/gitcredentials#_requesting_credentials). Looks like it checks `GIT_ASKPASS` environment var first, then the git config `core.askPass`, then `SSH_ASKPASS` environment var, then terminal prompt if nothing else is found.

Should this extension be trying to make the username and password prompts work or just treating the store as readonly as far as this extension is concerned? It looks like the VSCode Git extension uses `GIT_ASKPASS`, `VSCODE_GIT_ASKPASS_NODE` and `VSCODE_GIT_ASKPASS_MAIN`, which may be why I was getting inconsistencies only setting the `GIT_ASKPASS` var. https://github.com/microsoft/vscode/blob/master/extensions/git/src/askpass.ts#L75

I was doing a mix of trying from a nodejs script run from Powershell in VSCode, Powershell in Windows Terminal and the extension. Now I will try again and track what happens a little more organized, now that I know a little more about what is going on.

**Comment by Marklb** [comment]
In the PR I switched back to `execSync`, so it should allow the `git.bat` file to work again, in case that did happen to be how I primarily execute git. I didn't get it to prompt for credentials, but it should at least return an empty string if the credentials aren't set, instead of hanging.

The environment vars being inherited must have just meant for the terminal. If I run a script in the VSCode terminal it has the environment vars `GIT_ASKPASS`, `VSCODE_GIT_ASKPASS_NODE`, `VSCODE_GIT_ASKPASS_MAIN`, and `VSCODE_GIT_IPC_HANDLE`, but in the extension `execSync` had none of those set. I tried setting them in the extensions `execSync` call, but it still didn't give me a login prompt.

**Comment by idanpa** [comment]
Any workaround? Can't use gistpad (windows with git from WSL).

**Comment by Marklb** [comment]
@idanpa You could try my PR #156 or try adding git credentials from a terminal.
If you run the following nodejs script, it should either log your credentials or prompt to enter them. The issue I had was `execSync` getting hung by the prompt, because it was trying to ask for input and the extension wasn't noticing, so it just sat there waiting on a response and by using the synchronous `exec` function, the process could do nothing else until it finished waiting. If that is the problem you are having, then you should be fine once your git credentials store has credentials for github.
```node
const { execSync } = require('child_process')
const input = 'protocol=https\nhost=github.com\n\n'
const response = execSync("git credential fill", { input, encoding: "utf8" });
console.log(response)
```
If the script logged your credentials, then your problem may be different than the one I had. If you get the prompt, which may be a popup or in the terminal depending on the AskPass configuration, which I don't know a lot about, but I did explain it partially in previous comments.

**Comment by idanpa** [comment]
Thanks @Marklb,
Managed to solve this by storing git credentials like you suggested:
```
git config --global credential.helper store
```
And then doing some https git operation that required password

**Comment by lostintangent** [comment]
I just pushed an update to GistPad which disables the Git CLI SSO entirely by default. So if folks update to the latest version, this should hopefully unblock you. I'm going to close this issue as resolved, but please let me know if you're still running into issues.

Also, if you'd like to re-enable the Git CLI SSO for some reason, you can simply set the `GistPad: Git SSO` setting to `true`, and then reload VS Code. Thanks!
