### ISSUE TITLE
Comments panel keeps re-appearing after hiding

### ISSUE THREAD

**Issue by misolori** [vsls-contrib/gistpad#155]
**Describe the bug**
_Originally posted in https://github.com/microsoft/vscode/issues/99688_. The comments panel is always appearing even when I am not in any GistPad project. I explicitly hide the comments panel since I don't use/need it, but on reload it keeps appearing.

**To Reproduce**
1. Open panel
2. Hide "Comments" view
3. Reload
4. Comments view re-appears

**Expected behavior**
If I hide the comments view, do not make it re-appear. Would be better to have a setting to disable comments all together.

**Screenshots**
![Kapture 2020-06-09 at 8 37 12](https://user-images.githubusercontent.com/35271042/84168970-e6760a80-aa2c-11ea-8c00-57f70048fa83.gif)

**Desktop (please complete the following information):**
 - VS Code Version  1.46.0-insider
 - GistPad Version v0.0.68

**Comment by lostintangent** [comment]
Hmm interesting. Thanks for reporting this! I suppose I could try delaying the registration of the comment controller until you open a gist with any comments in it? That way at a minimum, this wouldn’t be a common occurrence. Additionally, I could definitely add a setting to disable comments all together 👍

That said, this also kind of seems like a bug in VS Code? If an extension registers a comment controller, but the end-user chooses to hide the comments panel, then I’d think that VS Code should respect the end-users wishes. Particularly since the comment controller doesn’t dictate whether or not the comments panel is or isn’t visible. @rebornix what do you think?

**Comment by lostintangent** [comment]
This issue should now be fixed, since VS Code seems to correctly persist the user's decision to hide the `Comments` panel now. Please re-open it if you're still running into an issue. Thanks!
