### ISSUE TITLE
Support for Github Wikis?

### ISSUE THREAD

**Issue by bs** [vsls-contrib/gistpad#186]
Would be amazing to be able to manage a repo/wiki.git.

**Comment by lostintangent** [comment]
Hey! I was hoping to enable this when I first added repo support, but GitHub doesn’t expose APIs for managing wikis unfortunately. And so instead of being able to edit repos entirely remotely, I believe GistPad would need to actually clone the wiki repo locally and then synchronize it with the server.

That’s definitely not the end of the world, but it’s not as nice as I’d hope it would be 😁 I’ll take another look at this tomorrow and see how simple it might be to add this 👍

**Comment by bs** [comment]
Ah, I see! I haven't poked at the [Github API](https://github.com/vsls-contrib/gistpad/blob/4c0acf4544c463984b9e83ad722857a4b36062c4/src/repos/store/actions.ts) before. Because it's a repo, I would have expected ```curl -i https://api.github.com/repos/earthspecies/project/wiki``` to work!

Aye, local clone isn't quite as elegant, but not the worst? On my end I'll likely use repos for wiki content.

**Comment by lostintangent** [comment]
After looking into this more, there's unfortunately not a way for me to remote edit a wiki, and it's a bit out of scope for GistPad to be cloning git repos locally and trying to sync them. For now, I'm going to close this, and focus entirely on gist and repo management. That said, if anyone in the community wanted to contributed support for this, I'd be more than happy to collaborate on that. Thanks!
