### ISSUE TITLE
I frequently have to sign in

### ISSUE THREAD

**Issue by majkinetor** [vsls-contrib/gistpad#197]
**Describe the bug**

Since maybe few months back, I need to re-sign in very often. Previously I never had to do that. I don't know when/why it happens.

**Expected behavior**

To never resign on single machine when token is valid.

**Desktop (please complete the following information):**
 - VS Code Version 1.50.1
 - GistPad Version 0.1.12

**Comment by lostintangent** [comment]
Hey! I actually just rewrote auth and published it a couple of days ago. So if you updated to the latest version, you would have been asked to sign in again, but the frequent sign outs should be fixed. So I'm going to close this for now, since this issue should be resolved. Please re-open it if you see this issue again, after using the new extension version for a few days. Thanks!
