### ISSUE TITLE
Sidebar improvements

### ISSUE THREAD

**Issue by IlanVivanco** [vsls-contrib/gistpad#28]
Some suggestion that came up while using the new sidebar.

- I would invert the order of the name – or even remove the file name – so that the Gist description appears first. The filename would appear anyway when you click the chevron.

- I would change the padlock to a gray-scale one, so it does not take too much attention to the eye. Maybe moving it to the start of the name?

![References](https://user-images.githubusercontent.com/9307840/69879782-1f2b6f00-12a7-11ea-8756-34f3bf8a723a.png)

**Comment by lostintangent** [comment]
Thoughts on this? It uses the Gist's description (if available) for the node label, otherwise it uses the filename. Additionally, I removed the lock icon, and simply add a "Secret" annotation to the right of secret gists.

I'm about to publish this change to the marketplace:

<img width="417" alt="Screen Shot 2019-11-29 at 8 23 27 AM" src="https://user-images.githubusercontent.com/116461/69881362-ae259080-1281-11ea-994b-a1b3f4b3ed7d.png">

**Comment by IlanVivanco** [comment]
Much more clear, No doubts! 👏

**Comment by lostintangent** [comment]
OK cool. This change is being published to the marketplace, so you should see the update for 0.0.8 in a couple of minutes. Let me know if you have any more feedback!

**Comment by lostintangent** [comment]
@IlanVivanco Also, if these changes end up working well for you, it would be hugely appreciated if you could leave a review in the marketplace 👍

**Comment by IlanVivanco** [comment]
Will do!
