### ISSUE TITLE
This extension installs other extensions without the knowledge and consent of the user.

### ISSUE THREAD

**Issue by viccher** [vsls-contrib/gistpad#35]
This extension is very good and useful, but without my knowledge and consent it installs Markdown extensions for me. As far as I understand, Markdown extensions are not needed for this extension to work. Markdown extensions may be useful, but I don't need them at the moment. So why do this? I do not like this. That is why I deleted this extension, although otherwise it is a very useful and good extension and I like it. I will install it after it stops installing other extensions I do not need.
Thanks.

**Comment by lostintangent** [comment]
It’s extremely common to use Gists for storing markdown files. Additionally, GitHub’s markdown experience supports features that VS Code doesn’t by default (e.g. rendering checkboxes). As a result, I wanted this extension to include the markdown tooling needed to have a productive consistent experience with the Gist web UI. 

This extension has a dependency on two extensions: Markdown Checkbox and Markdown All in One. Do you have a problem with both? The Checkbox extension literally just enhances the markdown previewer to render checkboxes in a task list. I’d be happy to remove the Markdown All In One dependency, but I’d love to keep the checkbox dependency is that isn’t a problem for folks (since it’s a feature of GitHub’s markdown support).

**Comment by lostintangent** [comment]
@viccher Just shipped v0.0.14, which removes the extension dependencies and adds them as recommendations to the readme. Let me know what you think!

**Comment by viccher** [comment]
> @viccher Just shipped v0.0.14, which removes the extension dependencies and adds them as recommendations to the readme. Let me know what you think!

I think this is the right decision.
Now users who install your extension will not be perplexed where they got the extensions that they did not install. And they won’t take the time to figure it out, since such behavior provokes a suspicion of a security breach.
Thanks you!
Regards and best wishes.
