### ISSUE TITLE
HTML Preview fails to load if css file is missing/deleted.

### ISSUE THREAD

**Issue by st0le** [vsls-contrib/gistpad#46]
Steps to repro
1) Create a new playground
2) Delete the css stylesheet. 
3) Save the Gist
4) Close the editor.
5) Open Fresh Editor and attempt to load the playground.

Result :
HTML Preview fails to load.

![image](https://user-images.githubusercontent.com/3803209/71288060-dce1d480-231e-11ea-93e6-a2da0fbba280.png)

**Comment by lostintangent** [comment]
Good find! Yeah I currently assume there is always a CSS file, so I’ll fix this today 👍As a workaround, you should be able to just right-click the gist, select add file, and recreate the “index.css” file. Stay tuned for a fix soon!

**Comment by lostintangent** [comment]
This has now been fixed and released to the marketplace. Thanks for the feedback!

Additionally, I added a new setting called `GistPad > Playground: Include Stylesheet` that you can set to `false` in order to prevent a CSS file from getting created in future playgrounds. Let me know how it works for you. Thanks~
