### ISSUE TITLE
Emmet macros or JS AutoComplete not available in playground.

### ISSUE THREAD

**Issue by st0le** [vsls-contrib/gistpad#47]
I can't seem to get any autocomplete in the HTML or JS file. 
Not sure if it's the extension or VSCode. I'm on the latest insider.

I've verified the language is set to HTML/JS respectively when the Tab is open.

**Comment by lostintangent** [comment]
Hey! This is due to #30. GistPad exposes a “virtual file system provider” to VS Code, where the files are actually backed by a Gist, not on disk. Unfortunately, many language features don’t work with these virtual file systems, and so I need to contribute to them in order to make them work.

JS is already in progress, and I’ll look at Emmett tonight 👍 These are just point in time issues, that I’m working through right now.

**Comment by st0le** [comment]
Dupe of #30
