### ISSUE TITLE
show gist as file if its a single file

### ISSUE THREAD

**Issue by ctf0** [vsls-contrib/gistpad#51]
atm all the gists are displayed as a group ex.`> some gist` even when its a single file.

so is it possible for those gists to show the file directly instead of having to first expand the group then open the gist ?

**Comment by aredcomet** [comment]
@lostintangent  is there any reason behind this design. As github gist's doesn't support directories.

**Comment by lostintangent** [comment]
@aredcomet A gist can contain multiple files, and you may only want to open/edit/delete/rename a specific file. Therefore, the tree structure enables a very flexible model. That said, I just added the "Open Gist" action as an inline button on the gist node, which would allow you to open the files for a gist in a single-click, without having to reduce the flexibility of multi-file nodes. The following is a screenshot of this: ![image](https://user-images.githubusercontent.com/116461/72094033-60f9fd00-32ca-11ea-972b-14c9c38c376d.png). Thoughts? Would this be a sufficient solution for your workflows?

**Comment by ctf0** [comment]
@lostintangent i believe this is the same as the `open gist` context menu

**Comment by lostintangent** [comment]
Yep it’s exactly the same. I thought your feedback was that you didn’t want to expand the tree node in order to open a file? With this action, you would have a single-click solution to opening gists, regardless if they’re single file or multi-file. Are you looking for something else?

Additionally, if you delete the description of the gist, then it’s description will become the name of the file in it. Are you also asking to be able to display the file name as the tree node label, for single-file gists that also have a description?

**Comment by ctf0** [comment]
not exactly because in case of multi files, using the btn will open all of theme, while what i was asking for is to show single file gist as a single file instead of a group.

**Comment by lostintangent** [comment]
I apologize, I’m still not entirely following you. Do you not want to see the gist’s description in the tree at all? And would rather just see the file name if the gist only contained a single file? If you delete the gist’s description, this is exactly what you would see. I just want to make sure I understand exactly what you’re trying to optimize for (e.g. presentation, ergonomics, etc.) so that I can weigh that with other user preferences.

**Comment by ctf0** [comment]
> And would rather just see the file name if the gist only contained a single file?

exactly

**Comment by lostintangent** [comment]
If you create a Gist right now, and don’t set a description (the description is optional), then the name of the Gist will be the name of the single-file   in the gist. So you could get your desired experience using the current version of GistPad.

That said, are you saying that you want to have a description for the gist, but that the name of the file is more descriptive to you? I’m only asking because the description is optional, since it’s meant to add more recognizable meaning to the files, _if_ the file name isn’t itself already meaningful on its own (e.g. index.html doesn’t mean anything without a description). So it seems like there are two potential solutions here:

1. People that want to see the file name vs. the description can simply not set a description when creating the gist. As I mentioned, this is the current behavior today

2. I could add a setting that allows users to choose between tree node label options, so they can control whether the gist node displays it’s description or the file name

#1 has the benefit of being config-free and responds to the users intent (e.g. you didn’t set a description, so you implicitly declared that you care more about the file name than the gist description). So it would be great to understand what your workflow looks like, and why you’re setting a description, but don’t want to actually see it.

Assuming #1 isn’t sufficient because you want to set a description, but still see the node using its file name, then I think #2 is the only option, that doesn’t force users into one specific opinion.

**Comment by ctf0** [comment]
i understand ur point, the #1 solution works perfectly but what about old gists, do u go through them one by one to remove the description ?

**Comment by lostintangent** [comment]
Yep I think #2 is totally reasonable. I’ll get to it this weekend and release an update. Thanks for talking this through with me 👍

**Comment by aredcomet** [comment]
@ctf0 Sorry for late response. btn to open all the files in the gist actually helps as I keep only one file in a gist (didn't knew that I can have multiple files in a gist).

#2 sound good however, I was browsing through other issues aswell, there is a mention of using hashtags to group the files and show only hashtags. That will be really awesome.

**Comment by ctf0** [comment]
@lostintangent the last update is perfect, just one last suggestion, can we have a different icon for single file gist ? this way you don't accidentally open multiple files gist all over the place

**Comment by lostintangent** [comment]
At this point, GistPad has a lot of users, and so I’d prefer to not change anything about the core UX. I’m going to close this issue since I haven’t heard other feedback for it, but please reopen if it you feel like we need to reconsider this enhancement. Thanks!
