### ISSUE TITLE
Expose "Open Gist in GitHub" command in the command palette

### ISSUE THREAD

**Issue by ctf0** [vsls-contrib/gistpad#64]
atm its only possible from the view menu

**Comment by lostintangent** [comment]
Thanks for reporting this! Are you primarily interested in this for playgrounds? Or for any gist? I just ask since we have commands for opening a Gist in GitHub, CodePen, NbViewer and GistLog. I’d love to make sure I know which one you’re interested in 👍

**Comment by ctf0** [comment]
yeah sure, for any gist.

also it will work for playground as it have the same gist id.

this is simply a replication of the view command but in the command palette for quicker access

**Comment by lostintangent** [comment]
Agreed. I just wanted to confirm that the exact behavior you want is to open the current gist in GitHub.com. It sounds like that’s what you want, so I’ll add that behavior 👍

**Comment by lostintangent** [comment]
I’d prefer not to add any more commands to the command palette, particularly since the GistPad tree view has become very complex, and therefore, is required for performing a lot of different operations. Since I haven’t heard any other feedback for this, I’m going to close it for now. Please reopen it if you feel like this is important enough to become prioritized over other work. Thanks!
