### ISSUE TITLE
Menu item references a command `gistpad.addPlaygroundScript` which is not defined in the 'commands' section.

### ISSUE THREAD

**Issue by ctf0** [vsls-contrib/gistpad#80]
https://github.com/vsls-contrib/gistpad/blob/15390a10efa1864ed8ce30d664841619b289dfe8/package.json#L836

**Comment by lostintangent** [comment]
Thanks for the heads up! This shouldn't break anything, but you're right, it's dead code at this point. Just pushed a fix 👍 

BTW, I had to revert your icon change, since that currently only works in VS Code insiders. So we'll need to keep the icon images around for at least a couple of months, since I don't want to require too new a version of VS Code.

**Comment by ctf0** [comment]
dam it, okay thanx for the headsup too.

happy new year btw, sorry it came kinda late 🎊
